services:
  - type: web
    name: aemet-avisos-zona-cache
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: AEMET_API_KEY
        value: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWltZUBtaXNzaW9udHJhY2suY29tIiwianRpIjoiMzQ1OWE5MmYtM2RmNS00NWQwLTgyNWYtNDA4ZWNjMzcxODkxIiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE3MDcwNDEwODYsInVzZXJJZCI6IjM0NTlhOTJmLTNkZjUtNDVkMC04MjVmLTQwOGVjYzM3MTg5MSIsInJvbGUiOiIifQ.Wg_hkuQdAlqVR8dbtbQgxIF5fAam1ehJ3-bDV27qgaA'
      - key: AEMET_AREAS
        value: "61,62,63,64,78,65,66,67,68,69,77,70,71,72,79,73,74,75,76"

  - type: cron
    name: aemet-avisos-zona-refresh
    schedule: "0 * * * *"      # cada hora, minuto 0
    env: docker
    dockerCommand: >
      curl -sS https://aemet-avisos-zona-cache.onrender.com/refresh
